import type { Recipe, Settings } from "./types";

export const defaultSettings: Settings = {
  id: "singleton",
  lang: "es",
  mode: "lazy",
  doublePortions: true,
  householdSize: 2,
  maxTimeMin: 25,
  maxCostTier: 2,
  noRepeatDays: 12,
};

// All quantities are for 4 servings (2 people x 2 meals: dinner + next day lunch)
export const seedRecipes: Recipe[] = [
  // ── MEDITERRANEAN / SPANISH ──
  {
    id: "pasta_atun_tomate",
    title: { es: "Pasta con atún y tomate", ca: "Pasta amb tonyina i tomàquet" },
    description: { es: "Rápida, barata y con proteína. Ideal para sobras.", ca: "Ràpida, econòmica i amb proteïna. Ideal per a sobres." },
    timeMin: 15,
    costTier: 1,
    difficulty: "easy",
    tags: ["quick", "budget", "pasta"],
    imageUrl: "https://images.unsplash.com/photo-1761545832779-bc0b4290fc5e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NzYzMDZ8MHwxfHNlYXJjaHwxfHx0dW5hJTIwdG9tYXRvJTIwcGFzdGElMjBkaXNofGVufDB8MHx8fDE3NzEyODU4MjZ8MA&ixlib=rb-4.1.0&q=80&w=1080",
    active: 1,
    ingredients: [
      { name: { es: "Pasta (penne o espaguetis)", ca: "Pasta (penne o espaguetis)" }, qty: 400, unit: "g", category: "carbs" },
      { name: { es: "Atún en lata", ca: "Tonyina en llauna" }, qty: 3, unit: "u", category: "cans" },
      { name: { es: "Tomate triturado", ca: "Tomàquet triturat" }, qty: 400, unit: "g", category: "cans" },
      { name: { es: "Ajo", ca: "All" }, qty: 3, unit: "diente", category: "produce", pantry: true },
      { name: { es: "Aceite de oliva", ca: "Oli d'oliva" }, qty: 2, unit: "cda", category: "sauces", pantry: true },
      { name: { es: "Orégano", ca: "Orenga" }, qty: 1, unit: "cdta", category: "spices", pantry: true },
    ],
    steps: {
      es: [
        "Hervir la pasta\n• Pon agua con sal a hervir y cuece la pasta según el paquete.\n• Reserva un vaso de agua de cocción antes de escurrir.",
        "Preparar la salsa\n• Sofríe el ajo picado en aceite 1 min.\n• Añade el tomate triturado, orégano, sal y pimienta.\n• Cocina 5 min a fuego medio.",
        "Mezclar todo\n• Escurre el atún y añádelo a la salsa.\n• Agrega la pasta y mezcla bien.\n• Si queda seco, añade un poco del agua de cocción.",
      ],
      ca: [
        "Bullir la pasta\n• Posa aigua amb sal a bullir i cou la pasta segons el paquet.\n• Reserva un got d'aigua de cocció abans d'escórrer.",
        "Preparar la salsa\n• Salteja l'all picat amb oli 1 min.\n• Afegeix el tomàquet triturat, orenga, sal i pebre.\n• Cuina 5 min a foc mitjà.",
        "Barrejar-ho tot\n• Escorre la tonyina i afegeix-la a la salsa.\n• Afegeix la pasta i barreja bé.\n• Si queda sec, afegeix una mica d'aigua de cocció.",
      ],
    },
  },
  {
    id: "wok_verduras_huevo",
    title: { es: "Wok de verduras con huevo", ca: "Wok de verdures amb ou" },
    description: { es: "Ultrarrápida con verduras congeladas y huevo.", ca: "Ultraràpida amb verdures congelades i ou." },
    timeMin: 12,
    costTier: 1,
    difficulty: "easy",
    tags: ["quick", "budget", "vegetarian"],
    imageUrl: "https://images.unsplash.com/photo-1606898425194-ea24a36480af?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NzYzMDZ8MHwxfHNlYXJjaHwxfHx2ZWdldGFibGUlMjBzdGlyJTIwZnJ5JTIwZWdnfGVufDB8MHx8fDE3NzEyODU4Mjh8MA&ixlib=rb-4.1.0&q=80&w=1080",
    active: 1,
    ingredients: [
      { name: { es: "Verduras congeladas para saltear", ca: "Verdures congelades per saltar" }, qty: 600, unit: "g", category: "produce" },
      { name: { es: "Huevos", ca: "Ous" }, qty: 4, unit: "u", category: "dairy" },
      { name: { es: "Arroz", ca: "Arròs" }, qty: 300, unit: "g", category: "carbs" },
      { name: { es: "Salsa de soja", ca: "Salsa de soja" }, qty: 3, unit: "cda", category: "sauces", pantry: true },
      { name: { es: "Aceite de oliva", ca: "Oli d'oliva" }, qty: 2, unit: "cda", category: "sauces", pantry: true },
    ],
    steps: {
      es: [
        "Preparar el arroz\n• Cuece el arroz según las instrucciones del paquete.\n• Escurre y reserva.",
        "Saltear las verduras\n• Calienta aceite a fuego fuerte en un wok o sartén grande.\n• Añade las verduras congeladas y saltea 5-6 min sin mover mucho.\n• Quieres que cojan color.",
        "Añadir huevo y terminar\n• Haz un hueco en el centro, casca los huevos y revuelve.\n• Cuando el huevo cuaje, mezcla todo con la salsa de soja.\n• Sirve sobre el arroz.",
      ],
      ca: [
        "Preparar l'arròs\n• Cou l'arròs segons les instruccions del paquet.\n• Escorre i reserva.",
        "Saltejar les verdures\n• Escalfa oli a foc fort en un wok o paella gran.\n• Afegeix les verdures congelades i salteja 5-6 min sense moure gaire.\n• Vols que agafin color.",
        "Afegir ou i acabar\n• Fes un forat al centre, trenca els ous i remena.\n• Quan l'ou qualli, barreja tot amb la salsa de soja.\n• Serveix sobre l'arròs.",
      ],
    },
  },
  {
    id: "pollo_limon_patatas",
    title: { es: "Pollo al limón con patatas", ca: "Pollastre al llimó amb patates" },
    description: { es: "Clásico mediterráneo, jugoso y fácil. Todo en una bandeja.", ca: "Clàssic mediterrani, sucós i fàcil. Tot en una safata." },
    timeMin: 30,
    costTier: 2,
    difficulty: "easy",
    tags: ["chicken", "mediterranean", "one-pan"],
    imageUrl: "https://images.unsplash.com/photo-1748819762564-21fc970cfa23?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NzYzMDZ8MHwxfHNlYXJjaHwxfHxsZW1vbiUyMGNoaWNrZW4lMjBwb3RhdG9lc3xlbnwwfDB8fHwxNzcxMjg1ODMwfDA&ixlib=rb-4.1.0&q=80&w=1080",
    active: 1,
    ingredients: [
      { name: { es: "Contramuslos de pollo", ca: "Contracuixes de pollastre" }, qty: 8, unit: "u", category: "meat" },
      { name: { es: "Patatas", ca: "Patates" }, qty: 600, unit: "g", category: "produce" },
      { name: { es: "Limón", ca: "Llimona" }, qty: 2, unit: "u", category: "produce" },
      { name: { es: "Ajo", ca: "All" }, qty: 4, unit: "diente", category: "produce", pantry: true },
      { name: { es: "Aceite de oliva", ca: "Oli d'oliva" }, qty: 3, unit: "cda", category: "sauces", pantry: true },
      { name: { es: "Orégano", ca: "Orenga" }, qty: 1, unit: "cdta", category: "spices", pantry: true },
    ],
    steps: {
      es: [
        "Preparar las patatas\n• Precalienta el horno a 210°C.\n• Corta las patatas en cuartos y ponlas en una bandeja de horno.\n• Aliña con aceite, sal, pimienta y orégano.",
        "Preparar el pollo\n• Salpimenta los contramuslos.\n• Exprime 1 limón por encima y coloca ajo picado.\n• Corta el otro limón en rodajas.",
        "Hornear\n• Pon el pollo sobre las patatas, piel arriba.\n• Distribuye las rodajas de limón alrededor.\n• Hornea 25-30 min hasta que la piel esté dorada y crujiente.",
      ],
      ca: [
        "Preparar les patates\n• Preescalfa el forn a 210°C.\n• Talla les patates en quarts i posa-les en una safata de forn.\n• Amaneix amb oli, sal, pebre i orenga.",
        "Preparar el pollastre\n• Salpebra les contracuixes.\n• Esprem 1 llimona per sobre i col·loca all picat.\n• Talla l'altra llimona en rodanxes.",
        "Enfornar\n• Posa el pollastre sobre les patates, pell amunt.\n• Distribueix les rodanxes de llimona al voltant.\n• Enforna 25-30 min fins que la pell estigui daurada i cruixent.",
      ],
    },
  },
  {
    id: "tortilla_espanola",
    title: { es: "Tortilla española", ca: "Truita espanyola" },
    description: { es: "La clásica tortilla de patatas. Pocillos, cenas y sobras.", ca: "La clàssica truita de patates. Per sopar i sobres." },
    timeMin: 25,
    costTier: 1,
    difficulty: "easy",
    tags: ["spanish", "vegetarian", "budget"],
    imageUrl: "https://images.unsplash.com/photo-1607877200978-3cab430e00cd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NzYzMDZ8MHwxfHNlYXJjaHwxfHxzcGFuaXNoJTIwb21lbGV0dGUlMjB0b3J0aWxsYXxlbnwwfDB8fHwxNzcxMjg1ODMxfDA&ixlib=rb-4.1.0&q=80&w=1080",
    active: 1,
    ingredients: [
      { name: { es: "Patatas", ca: "Patates" }, qty: 600, unit: "g", category: "produce" },
      { name: { es: "Huevos", ca: "Ous" }, qty: 8, unit: "u", category: "dairy" },
      { name: { es: "Cebolla", ca: "Ceba" }, qty: 1, unit: "u", category: "produce" },
      { name: { es: "Aceite de oliva", ca: "Oli d'oliva" }, qty: 150, unit: "ml", category: "sauces", pantry: true },
      { name: { es: "Sal", ca: "Sal" }, qty: 1, unit: "cdta", category: "spices", pantry: true },
    ],
    steps: {
      es: [
        "Freír patata y cebolla\n• Pela y corta las patatas en láminas finas.\n• Corta la cebolla en juliana.\n• Fríe todo en abundante aceite a fuego medio-bajo 15 min, que quede tierno pero no crujiente.",
        "Mezclar con huevo\n• Bate los huevos con sal en un bol grande.\n• Escurre bien las patatas del aceite.\n• Mezcla patatas con los huevos y deja reposar 5 min.",
        "Cuajar la tortilla\n• En sartén antiadherente con poco aceite, vierte la mezcla.\n• Cocina a fuego medio-bajo 4-5 min.\n• Dale la vuelta con un plato y cocina 3 min más.\n_CONSEJO: Si te gusta jugosa, menos tiempo por el segundo lado._",
      ],
      ca: [
        "Fregir patata i ceba\n• Pela i talla les patates en làmines fines.\n• Talla la ceba en juliana.\n• Fregeix tot amb abundant oli a foc mitjà-baix 15 min, que quedi tendre però no cruixent.",
        "Barrejar amb ou\n• Bat els ous amb sal en un bol gran.\n• Escorre bé les patates de l'oli.\n• Barreja patates amb els ous i deixa reposar 5 min.",
        "Quallar la truita\n• En paella antiadherent amb poc oli, aboca la barreja.\n• Cuina a foc mitjà-baix 4-5 min.\n• Dona la volta amb un plat i cuina 3 min més.\n_CONSELL: Si t'agrada sucosa, menys temps pel segon costat._",
      ],
    },
  },
  {
    id: "garbanzos_espinacas",
    title: { es: "Garbanzos con espinacas", ca: "Cigrons amb espinacs" },
    description: { es: "Plato de cuchara rápido, nutritivo y barato.", ca: "Plat de cullera ràpid, nutritiu i econòmic." },
    timeMin: 15,
    costTier: 1,
    difficulty: "easy",
    tags: ["quick", "budget", "vegetarian", "spanish"],
    imageUrl: "https://images.unsplash.com/photo-1612108438004-257c47560118?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NzYzMDZ8MHwxfHNlYXJjaHwxfHxjaGlja3BlYXMlMjBzcGluYWNoJTIwc3Rld3xlbnwwfDB8fHwxNzcxMjg1ODM0fDA&ixlib=rb-4.1.0&q=80&w=1080",
    active: 1,
    ingredients: [
      { name: { es: "Garbanzos cocidos (bote)", ca: "Cigrons cuits (pot)" }, qty: 2, unit: "u", category: "cans" },
      { name: { es: "Espinacas frescas", ca: "Espinacs frescos" }, qty: 300, unit: "g", category: "produce" },
      { name: { es: "Ajo", ca: "All" }, qty: 3, unit: "diente", category: "produce", pantry: true },
      { name: { es: "Pimentón", ca: "Pebre vermell" }, qty: 1, unit: "cdta", category: "spices", pantry: true },
      { name: { es: "Comino", ca: "Comí" }, qty: 0.5, unit: "cdta", category: "spices", pantry: true },
      { name: { es: "Aceite de oliva", ca: "Oli d'oliva" }, qty: 3, unit: "cda", category: "sauces", pantry: true },
      { name: { es: "Pan", ca: "Pa" }, qty: 4, unit: "rebanada", category: "carbs" },
    ],
    steps: {
      es: [
        "Sofreír aromáticos\n• Calienta aceite y dora el ajo en láminas.\n• Añade pimentón y comino, remueve 30 seg.\n_CONSEJO: No quemes el pimentón, se amarga._",
        "Añadir garbanzos y espinacas\n• Escurre los garbanzos y añádelos a la sartén.\n• Agrega las espinacas y un chorrito de agua.\n• Cocina 5 min a fuego medio hasta que las espinacas se reduzcan.",
        "Servir\n• Ajusta de sal y un chorrito de vinagre si quieres.\n• Sirve con pan tostado para mojar.",
      ],
      ca: [
        "Sofregir aromàtics\n• Escalfa oli i daura l'all en làmines.\n• Afegeix pebre vermell i comí, remena 30 seg.\n_CONSELL: No cremis el pebre vermell, s'amarga._",
        "Afegir cigrons i espinacs\n• Escorre els cigrons i afegeix-los a la paella.\n• Agrega els espinacs i un raig d'aigua.\n• Cuina 5 min a foc mitjà fins que els espinacs es redueixin.",
        "Servir\n• Ajusta de sal i un raig de vinagre si vols.\n• Serveix amb pa torrat per sucar.",
      ],
    },
  },
  {
    id: "risotto_champinones",
    title: { es: "Risotto de champiñones", ca: "Risotto de xampinyons" },
    description: { es: "Cremoso y reconfortante. Parece complejo pero es solo paciencia.", ca: "Cremós i reconfortant. Sembla complex però és només paciència." },
    timeMin: 30,
    costTier: 2,
    difficulty: "easy",
    tags: ["italian", "vegetarian", "comfort"],
    imageUrl: "https://images.unsplash.com/photo-1633964913295-ceb43826e7c9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NzYzMDZ8MHwxfHNlYXJjaHwxfHxtdXNocm9vbSUyMHJpc290dG98ZW58MHwwfHx8MTc3MTI4NTgzNXww&ixlib=rb-4.1.0&q=80&w=1080",
    active: 1,
    ingredients: [
      { name: { es: "Arroz arborio o bomba", ca: "Arròs arbori o bomba" }, qty: 350, unit: "g", category: "carbs" },
      { name: { es: "Champiñones", ca: "Xampinyons" }, qty: 400, unit: "g", category: "produce" },
      { name: { es: "Cebolla", ca: "Ceba" }, qty: 1, unit: "u", category: "produce" },
      { name: { es: "Caldo de verduras", ca: "Brou de verdures" }, qty: 1, unit: "L", category: "other" },
      { name: { es: "Queso parmesano", ca: "Formatge parmesà" }, qty: 60, unit: "g", category: "dairy" },
      { name: { es: "Mantequilla", ca: "Mantega" }, qty: 30, unit: "g", category: "dairy" },
      { name: { es: "Aceite de oliva", ca: "Oli d'oliva" }, qty: 2, unit: "cda", category: "sauces", pantry: true },
    ],
    steps: {
      es: [
        "Preparar ingredientes\n• Lamina los champiñones y pica la cebolla fina.\n• Calienta el caldo y mantenlo caliente.\n• Ralla el parmesano.",
        "Sofreír y tostar arroz\n• Sofríe la cebolla en aceite 3 min.\n• Añade los champiñones y cocina 4 min hasta que suelten agua.\n• Agrega el arroz y tuesta 1 min removiendo.",
        "Cocinar el risotto\n• Añade caldo caliente un cucharón a la vez.\n• Remueve y espera a que absorba antes de añadir más.\n• Repite durante 18-20 min hasta que el arroz esté al dente.",
        "Mantecar\n• Retira del fuego.\n• Añade mantequilla y parmesano rallado.\n• Remueve vigorosamente hasta que quede cremoso.\n• Ajusta sal y sirve inmediatamente.",
      ],
      ca: [
        "Preparar ingredients\n• Lamina els xampinyons i pica la ceba fina.\n• Escalfa el brou i mantén-lo calent.\n• Ratlla el parmesà.",
        "Sofregir i torrar arròs\n• Sofregeix la ceba amb oli 3 min.\n• Afegeix els xampinyons i cuina 4 min fins que deixin anar aigua.\n• Agrega l'arròs i torra 1 min remenant.",
        "Cuinar el risotto\n• Afegeix brou calent un cullerot a la vegada.\n• Remena i espera que absorbeixi abans d'afegir-ne més.\n• Repeteix durant 18-20 min fins que l'arròs estigui al dente.",
        "Mantecar\n• Retira del foc.\n• Afegeix mantega i parmesà ratllat.\n• Remena vigorosament fins que quedi cremós.\n• Ajusta sal i serveix immediatament.",
      ],
    },
  },
  // ── INTERNATIONAL ──
  {
    id: "pad_thai_express",
    title: { es: "Pad Thai express", ca: "Pad Thai exprés" },
    description: { es: "Versión rápida del clásico tailandés con pollo.", ca: "Versió ràpida del clàssic tailandès amb pollastre." },
    timeMin: 20,
    costTier: 2,
    difficulty: "easy",
    tags: ["asian", "quick", "chicken"],
    imageUrl: "https://images.unsplash.com/photo-1757845301558-e8e7dd41bc64?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NzYzMDZ8MHwxfHNlYXJjaHwxfHxwYWQlMjB0aGFpJTIwbm9vZGxlc3xlbnwwfDB8fHwxNzcxMjg1ODM3fDA&ixlib=rb-4.1.0&q=80&w=1080",
    active: 1,
    ingredients: [
      { name: { es: "Fideos de arroz", ca: "Fideus d'arròs" }, qty: 300, unit: "g", category: "carbs" },
      { name: { es: "Pechuga de pollo", ca: "Pit de pollastre" }, qty: 400, unit: "g", category: "meat" },
      { name: { es: "Huevos", ca: "Ous" }, qty: 3, unit: "u", category: "dairy" },
      { name: { es: "Cacahuetes tostados", ca: "Cacauets torrats" }, qty: 50, unit: "g", category: "nuts" },
      { name: { es: "Lima", ca: "Llima" }, qty: 2, unit: "u", category: "produce" },
      { name: { es: "Salsa de soja", ca: "Salsa de soja" }, qty: 3, unit: "cda", category: "sauces", pantry: true },
      { name: { es: "Azúcar moreno", ca: "Sucre morè" }, qty: 1, unit: "cda", category: "spices", pantry: true },
      { name: { es: "Aceite", ca: "Oli" }, qty: 2, unit: "cda", category: "sauces", pantry: true },
    ],
    steps: {
      es: [
        "Preparar fideos\n• Remoja los fideos de arroz en agua caliente 8-10 min.\n• Escurre y reserva.",
        "Cocinar el pollo\n• Corta el pollo en tiras finas.\n• Saltea en aceite a fuego fuerte 4-5 min.\n• Retira y reserva.",
        "Montar el pad thai\n• En la misma sartén, bate los huevos y revuelve.\n• Añade los fideos, el pollo, soja y azúcar.\n• Saltea 2-3 min mezclando bien.",
        "Servir\n• Sirve con cacahuetes picados y zumo de lima.\n• Acompaña con rodajas de lima extra.",
      ],
      ca: [
        "Preparar fideus\n• Remulla els fideus d'arròs en aigua calenta 8-10 min.\n• Escorre i reserva.",
        "Cuinar el pollastre\n• Talla el pollastre en tires fines.\n• Salteja amb oli a foc fort 4-5 min.\n• Retira i reserva.",
        "Muntar el pad thai\n• A la mateixa paella, bat els ous i remena.\n• Afegeix els fideus, el pollastre, soja i sucre.\n• Salteja 2-3 min barrejant bé.",
        "Servir\n• Serveix amb cacauets picats i suc de llima.\n• Acompanya amb rodanxes de llima extra.",
      ],
    },
  },
  {
    id: "tacos_pollo_aguacate",
    title: { es: "Tacos de pollo con aguacate", ca: "Tacos de pollastre amb alvocat" },
    description: { es: "Mexicano rápido para entre semana. Fresco y lleno de sabor.", ca: "Mexicà ràpid per entre setmana. Fresc i ple de sabor." },
    timeMin: 20,
    costTier: 2,
    difficulty: "easy",
    tags: ["mexican", "quick", "chicken"],
    imageUrl: "https://images.unsplash.com/photo-1614903754982-f2640e02efac?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NzYzMDZ8MHwxfHNlYXJjaHwxfHxjaGlja2VuJTIwdGFjb3MlMjBhdm9jYWRvfGVufDB8MHx8fDE3NzEyODU4Mzl8MA&ixlib=rb-4.1.0&q=80&w=1080",
    active: 1,
    ingredients: [
      { name: { es: "Pechuga de pollo", ca: "Pit de pollastre" }, qty: 500, unit: "g", category: "meat" },
      { name: { es: "Tortillas de trigo", ca: "Tortilles de blat" }, qty: 8, unit: "u", category: "carbs" },
      { name: { es: "Aguacate", ca: "Alvocat" }, qty: 2, unit: "u", category: "produce" },
      { name: { es: "Lima", ca: "Llima" }, qty: 1, unit: "u", category: "produce" },
      { name: { es: "Tomate", ca: "Tomàquet" }, qty: 2, unit: "u", category: "produce" },
      { name: { es: "Comino", ca: "Comí" }, qty: 1, unit: "cdta", category: "spices", pantry: true },
      { name: { es: "Pimentón", ca: "Pebre vermell" }, qty: 1, unit: "cdta", category: "spices", pantry: true },
      { name: { es: "Aceite de oliva", ca: "Oli d'oliva" }, qty: 2, unit: "cda", category: "sauces", pantry: true },
    ],
    steps: {
      es: [
        "Cocinar el pollo\n• Corta el pollo en dados.\n• Mezcla con comino, pimentón, sal y aceite.\n• Saltea a fuego fuerte 6-7 min hasta que esté dorado.",
        "Preparar el guacamole\n• Machaca los aguacates con un tenedor.\n• Añade zumo de lima, sal y tomate picado.\n• Mezcla bien.",
        "Montar los tacos\n• Calienta las tortillas en sartén seca 30 seg por lado.\n• Rellena con pollo y guacamole.\n• Sirve con lima extra.",
      ],
      ca: [
        "Cuinar el pollastre\n• Talla el pollastre en daus.\n• Barreja amb comí, pebre vermell, sal i oli.\n• Salteja a foc fort 6-7 min fins que estigui daurat.",
        "Preparar el guacamole\n• Xafa els alvocats amb una forquilla.\n• Afegeix suc de llima, sal i tomàquet picat.\n• Barreja bé.",
        "Muntar els tacos\n• Escalfa les tortilles en paella seca 30 seg per costat.\n• Farceix amb pollastre i guacamole.\n• Serveix amb llima extra.",
      ],
    },
  },
  {
    id: "curry_rojo_gambas",
    title: { es: "Curry rojo de gambas", ca: "Curry vermell de gambes" },
    description: { es: "Curry tailandés express con leche de coco y gambas.", ca: "Curry tailandès exprés amb llet de coco i gambes." },
    timeMin: 18,
    costTier: 2,
    difficulty: "easy",
    tags: ["asian", "quick", "seafood"],
    imageUrl: "https://images.unsplash.com/photo-1761545832792-535fafbad368?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NzYzMDZ8MHwxfHNlYXJjaHwxfHxyZWQlMjBjdXJyeSUyMHNocmltcHxlbnwwfDB8fHwxNzcxMjg1ODQxfDA&ixlib=rb-4.1.0&q=80&w=1080",
    active: 1,
    ingredients: [
      { name: { es: "Gambas peladas", ca: "Gambes pelades" }, qty: 500, unit: "g", category: "fish" },
      { name: { es: "Leche de coco", ca: "Llet de coco" }, qty: 400, unit: "ml", category: "cans" },
      { name: { es: "Pasta de curry rojo", ca: "Pasta de curry vermell" }, qty: 3, unit: "cda", category: "sauces" },
      { name: { es: "Pimiento rojo", ca: "Pebrot vermell" }, qty: 2, unit: "u", category: "produce" },
      { name: { es: "Arroz basmati", ca: "Arròs basmati" }, qty: 300, unit: "g", category: "carbs" },
      { name: { es: "Salsa de soja", ca: "Salsa de soja" }, qty: 1, unit: "cda", category: "sauces", pantry: true },
    ],
    steps: {
      es: [
        "Preparar el arroz\n• Pon el arroz basmati a cocer según el paquete.\n• Escurre y reserva.",
        "Hacer el curry\n• Calienta un poco de leche de coco en sartén y fríe la pasta de curry 1 min.\n• Añade el resto de leche de coco y los pimientos en tiras.\n• Cocina 5 min.",
        "Añadir las gambas\n• Agrega las gambas y salsa de soja.\n• Cocina 3-4 min hasta que las gambas estén rosadas.\n• Sirve sobre el arroz.",
      ],
      ca: [
        "Preparar l'arròs\n• Posa l'arròs basmati a coure segons el paquet.\n• Escorre i reserva.",
        "Fer el curry\n• Escalfa una mica de llet de coco en paella i fregeix la pasta de curry 1 min.\n• Afegeix la resta de llet de coco i els pebrots en tires.\n• Cuina 5 min.",
        "Afegir les gambes\n• Agrega les gambes i salsa de soja.\n• Cuina 3-4 min fins que les gambes estiguin rosades.\n• Serveix sobre l'arròs.",
      ],
    },
  },
  {
    id: "shakshuka",
    title: { es: "Shakshuka", ca: "Shakshuka" },
    description: { es: "Huevos escalfados en salsa de tomate especiada. Norte de África en tu sartén.", ca: "Ous escalfats en salsa de tomàquet especiada. Nord d'Àfrica a la teva paella." },
    timeMin: 20,
    costTier: 1,
    difficulty: "easy",
    tags: ["middle-eastern", "vegetarian", "budget", "one-pan"],
    imageUrl: "https://images.unsplash.com/photo-1614570218825-c2a3be79b0fd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NzYzMDZ8MHwxfHNlYXJjaHwxfHxzaGFrc2h1a2ElMjBlZ2dzfGVufDB8MHx8fDE3NzEyODU4NDN8MA&ixlib=rb-4.1.0&q=80&w=1080",
    active: 1,
    ingredients: [
      { name: { es: "Huevos", ca: "Ous" }, qty: 6, unit: "u", category: "dairy" },
      { name: { es: "Tomate triturado", ca: "Tomàquet triturat" }, qty: 600, unit: "g", category: "cans" },
      { name: { es: "Cebolla", ca: "Ceba" }, qty: 1, unit: "u", category: "produce" },
      { name: { es: "Pimiento rojo", ca: "Pebrot vermell" }, qty: 1, unit: "u", category: "produce" },
      { name: { es: "Ajo", ca: "All" }, qty: 3, unit: "diente", category: "produce", pantry: true },
      { name: { es: "Comino", ca: "Comí" }, qty: 1, unit: "cdta", category: "spices", pantry: true },
      { name: { es: "Pimentón", ca: "Pebre vermell" }, qty: 1, unit: "cdta", category: "spices", pantry: true },
      { name: { es: "Pan", ca: "Pa" }, qty: 1, unit: "u", category: "carbs" },
      { name: { es: "Aceite de oliva", ca: "Oli d'oliva" }, qty: 2, unit: "cda", category: "sauces", pantry: true },
    ],
    steps: {
      es: [
        "Preparar la base\n• Pica la cebolla, el pimiento y el ajo.\n• Sofríe en aceite 5 min hasta que ablande.",
        "Hacer la salsa\n• Añade comino y pimentón, remueve 30 seg.\n• Agrega el tomate triturado, sal y pimienta.\n• Cocina 8 min a fuego medio hasta que espese.",
        "Escalfar los huevos\n• Haz 6 huecos en la salsa con una cuchara.\n• Casca un huevo en cada hueco.\n• Tapa y cocina 5-6 min hasta que la clara cuaje.\n• Sirve directo de la sartén con pan para mojar.",
      ],
      ca: [
        "Preparar la base\n• Pica la ceba, el pebrot i l'all.\n• Sofregeix amb oli 5 min fins que estovi.",
        "Fer la salsa\n• Afegeix comí i pebre vermell, remena 30 seg.\n• Agrega el tomàquet triturat, sal i pebre.\n• Cuina 8 min a foc mitjà fins que espesseixi.",
        "Escalfar els ous\n• Fes 6 forats a la salsa amb una cullera.\n• Trenca un ou a cada forat.\n• Tapa i cuina 5-6 min fins que la clara qualli.\n• Serveix directe de la paella amb pa per sucar.",
      ],
    },
  },
  {
    id: "bibimbap_facil",
    title: { es: "Bibimbap fácil", ca: "Bibimbap fàcil" },
    description: { es: "Bol coreano con arroz, verduras, huevo y salsa picante.", ca: "Bol coreà amb arròs, verdures, ou i salsa picant." },
    timeMin: 25,
    costTier: 1,
    difficulty: "easy",
    tags: ["korean", "budget", "rice"],
    imageUrl: "https://images.unsplash.com/photo-1600289031464-74d374b64991?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NzYzMDZ8MHwxfHNlYXJjaHwxfHxiaWJpbWJhcCUyMGtvcmVhbiUyMHJpY2UlMjBib3dsfGVufDB8MHx8fDE3NzEyODU4NDR8MA&ixlib=rb-4.1.0&q=80&w=1080",
    active: 1,
    ingredients: [
      { name: { es: "Arroz", ca: "Arròs" }, qty: 300, unit: "g", category: "carbs" },
      { name: { es: "Carne picada de ternera", ca: "Carn picada de vedella" }, qty: 300, unit: "g", category: "meat" },
      { name: { es: "Zanahoria", ca: "Pastanaga" }, qty: 2, unit: "u", category: "produce" },
      { name: { es: "Calabacín", ca: "Carbassó" }, qty: 1, unit: "u", category: "produce" },
      { name: { es: "Espinacas", ca: "Espinacs" }, qty: 150, unit: "g", category: "produce" },
      { name: { es: "Huevos", ca: "Ous" }, qty: 4, unit: "u", category: "dairy" },
      { name: { es: "Salsa de soja", ca: "Salsa de soja" }, qty: 3, unit: "cda", category: "sauces", pantry: true },
      { name: { es: "Sriracha o gochujang", ca: "Sriracha o gochujang" }, qty: 2, unit: "cda", category: "sauces" },
      { name: { es: "Aceite de sésamo", ca: "Oli de sèsam" }, qty: 1, unit: "cda", category: "sauces" },
    ],
    steps: {
      es: [
        "Preparar arroz y carne\n• Cuece el arroz y reserva.\n• Saltea la carne con soja y aceite de sésamo 5 min.\n• Reserva.",
        "Saltear verduras\n• Corta zanahoria y calabacín en juliana.\n• Saltea cada verdura por separado 2-3 min con un poco de aceite y sal.\n• Blanquea las espinacas 1 min y escurre.",
        "Montar los boles\n• Pon arroz en el fondo de cada bol.\n• Coloca las verduras y la carne en secciones.\n• Fríe los huevos (con yema blanda) y ponlos encima.\n• Sirve con sriracha o gochujang al lado.",
      ],
      ca: [
        "Preparar arròs i carn\n• Cou l'arròs i reserva.\n• Salteja la carn amb soja i oli de sèsam 5 min.\n• Reserva.",
        "Saltejar verdures\n• Talla pastanaga i carbassó en juliana.\n• Salteja cada verdura per separat 2-3 min amb una mica d'oli i sal.\n• Blanqueja els espinacs 1 min i escorre.",
        "Muntar els bols\n• Posa arròs al fons de cada bol.\n• Col·loca les verdures i la carn en seccions.\n• Fregeix els ous (amb rovell tou) i posa'ls a sobre.\n• Serveix amb sriracha o gochujang al costat.",
      ],
    },
  },
  {
    id: "pasta_carbonara",
    title: { es: "Pasta carbonara auténtica", ca: "Pasta carbonara autèntica" },
    description: { es: "La verdadera carbonara: huevo, queso, guanciale. Sin nata.", ca: "La veritable carbonara: ou, formatge, guanciale. Sense nata." },
    timeMin: 20,
    costTier: 2,
    difficulty: "easy",
    tags: ["italian", "pasta", "quick"],
    imageUrl: "https://images.unsplash.com/photo-1588013273468-315fd88ea34c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NzYzMDZ8MHwxfHNlYXJjaHwxfHxwYXN0YSUyMGNhcmJvbmFyYXxlbnwwfDB8fHwxNzcxMjg1ODQ2fDA&ixlib=rb-4.1.0&q=80&w=1080",
    active: 1,
    ingredients: [
      { name: { es: "Espaguetis", ca: "Espaguetis" }, qty: 400, unit: "g", category: "carbs" },
      { name: { es: "Panceta o bacon", ca: "Panceta o bacon" }, qty: 200, unit: "g", category: "meat" },
      { name: { es: "Huevos", ca: "Ous" }, qty: 4, unit: "u", category: "dairy" },
      { name: { es: "Queso parmesano", ca: "Formatge parmesà" }, qty: 80, unit: "g", category: "dairy" },
      { name: { es: "Pimienta negra", ca: "Pebre negre" }, qty: 1, unit: "cdta", category: "spices", pantry: true },
    ],
    steps: {
      es: [
        "Preparar la salsa\n• Bate los huevos enteros con el parmesano rallado.\n• Añade abundante pimienta negra.\n• Reserva.",
        "Cocinar pasta y panceta\n• Cuece los espaguetis al dente. Reserva un vaso de agua de cocción.\n• Mientras, corta la panceta en dados y fríe sin aceite hasta que esté crujiente.",
        "Mezclar fuera del fuego\n• Escurre la pasta y ponla en la sartén con la panceta.\n• Retira del fuego.\n• Vierte la mezcla de huevo y remueve rápido.\n• Añade agua de cocción poco a poco hasta conseguir una crema sedosa.\n_CONSEJO: Nunca añadas el huevo con el fuego encendido o harás huevo revuelto._",
      ],
      ca: [
        "Preparar la salsa\n• Bat els ous sencers amb el parmesà ratllat.\n• Afegeix abundant pebre negre.\n• Reserva.",
        "Cuinar pasta i panceta\n• Cou els espaguetis al dente. Reserva un got d'aigua de cocció.\n• Mentrestant, talla la panceta en daus i fregeix sense oli fins que estigui cruixent.",
        "Barrejar fora del foc\n• Escorre la pasta i posa-la a la paella amb la panceta.\n• Retira del foc.\n• Aboca la barreja d'ou i remena ràpid.\n• Afegeix aigua de cocció poc a poc fins a aconseguir una crema sedosa.\n_CONSELL: Mai afegeixis l'ou amb el foc encès o faràs ou remenat._",
      ],
    },
  },
  {
    id: "salmon_teriyaki",
    title: { es: "Salmón teriyaki con arroz", ca: "Salmó teriyaki amb arròs" },
    description: { es: "Glaseado dulce-salado japonés. Elegante y en 20 min.", ca: "Glacejat dolç-salat japonès. Elegant i en 20 min." },
    timeMin: 20,
    costTier: 3,
    difficulty: "easy",
    tags: ["japanese", "fish", "quick"],
    imageUrl: "https://images.unsplash.com/photo-1685079258536-06d8253e862c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NzYzMDZ8MHwxfHNlYXJjaHwxfHx0ZXJpeWFraSUyMHNhbG1vbiUyMHJpY2V8ZW58MHwwfHx8MTc3MTI4NTg0OHww&ixlib=rb-4.1.0&q=80&w=1080",
    active: 1,
    ingredients: [
      { name: { es: "Lomos de salmón", ca: "Lloms de salmó" }, qty: 4, unit: "u", category: "fish" },
      { name: { es: "Arroz", ca: "Arròs" }, qty: 300, unit: "g", category: "carbs" },
      { name: { es: "Salsa de soja", ca: "Salsa de soja" }, qty: 4, unit: "cda", category: "sauces", pantry: true },
      { name: { es: "Miel", ca: "Mel" }, qty: 2, unit: "cda", category: "sauces", pantry: true },
      { name: { es: "Aceite de sésamo", ca: "Oli de sèsam" }, qty: 1, unit: "cda", category: "sauces" },
      { name: { es: "Brócoli", ca: "Bròcoli" }, qty: 300, unit: "g", category: "produce" },
    ],
    steps: {
      es: [
        "Preparar arroz y brócoli\n• Cuece el arroz según el paquete.\n• Cuece el brócoli al vapor o hervido 4 min. Que quede al dente.",
        "Hacer salsa teriyaki\n• Mezcla soja, miel y aceite de sésamo.",
        "Cocinar el salmón\n• Salpimenta los lomos.\n• Cocina en sartén con poco aceite, piel abajo, 4 min.\n• Dale la vuelta, vierte la salsa teriyaki y cocina 3 min más.\n• La salsa se reducirá y glaseará el salmón.\n• Sirve sobre arroz con brócoli al lado.",
      ],
      ca: [
        "Preparar arròs i bròcoli\n• Cou l'arròs segons el paquet.\n• Cou el bròcoli al vapor o bullit 4 min. Que quedi al dente.",
        "Fer salsa teriyaki\n• Barreja soja, mel i oli de sèsam.",
        "Cuinar el salmó\n• Salpebra els lloms.\n• Cuina en paella amb poc oli, pell avall, 4 min.\n• Dona la volta, aboca la salsa teriyaki i cuina 3 min més.\n• La salsa es reduirà i glacejarà el salmó.\n• Serveix sobre arròs amb bròcoli al costat.",
      ],
    },
  },
  {
    id: "falafel_pita",
    title: { es: "Falafel rápido con pita", ca: "Falafel ràpid amb pita" },
    description: { es: "Falafel de bote (truco rápido) con salsa de yogur.", ca: "Falafel de pot (truc ràpid) amb salsa de iogurt." },
    timeMin: 20,
    costTier: 1,
    difficulty: "easy",
    tags: ["middle-eastern", "vegetarian", "budget"],
    imageUrl: "https://images.unsplash.com/photo-1768812910769-d037b90aee77?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NzYzMDZ8MHwxfHNlYXJjaHwxfHxmYWxhZmVsJTIwcGl0YXxlbnwwfDB8fHwxNzcxMjg1ODUwfDA&ixlib=rb-4.1.0&q=80&w=1080",
    active: 1,
    ingredients: [
      { name: { es: "Garbanzos cocidos (bote)", ca: "Cigrons cuits (pot)" }, qty: 2, unit: "u", category: "cans" },
      { name: { es: "Pan de pita", ca: "Pa de pita" }, qty: 4, unit: "u", category: "carbs" },
      { name: { es: "Yogur natural", ca: "Iogurt natural" }, qty: 200, unit: "g", category: "dairy" },
      { name: { es: "Ajo", ca: "All" }, qty: 2, unit: "diente", category: "produce", pantry: true },
      { name: { es: "Comino", ca: "Comí" }, qty: 1, unit: "cdta", category: "spices", pantry: true },
      { name: { es: "Tomate", ca: "Tomàquet" }, qty: 2, unit: "u", category: "produce" },
      { name: { es: "Lechuga", ca: "Enciam" }, qty: 1, unit: "u", category: "produce" },
      { name: { es: "Aceite de oliva", ca: "Oli d'oliva" }, qty: 4, unit: "cda", category: "sauces", pantry: true },
    ],
    steps: {
      es: [
        "Hacer falafel\n• Escurre bien los garbanzos y tritúralos con tenedor (no quieres puré, quieres textura).\n• Mezcla con ajo picado, comino, sal y pimienta.\n• Forma bolitas y aplánalas un poco.",
        "Freír\n• Fríe los falafel en abundante aceite 3-4 min por lado.\n• Escurre en papel de cocina.",
        "Montar\n• Mezcla yogur con ajo rallado y sal para la salsa.\n• Calienta las pitas.\n• Rellena con falafel, lechuga, tomate y salsa de yogur.",
      ],
      ca: [
        "Fer falafel\n• Escorre bé els cigrons i tritura'ls amb forquilla (no vols puré, vols textura).\n• Barreja amb all picat, comí, sal i pebre.\n• Forma boletes i aplana-les una mica.",
        "Fregir\n• Fregeix els falafel amb abundant oli 3-4 min per costat.\n• Escorre en paper de cuina.",
        "Muntar\n• Barreja iogurt amb all ratllat i sal per a la salsa.\n• Escalfa les pites.\n• Farceix amb falafel, enciam, tomàquet i salsa de iogurt.",
      ],
    },
  },
  {
    id: "quesadillas_pollo",
    title: { es: "Quesadillas de pollo", ca: "Quesadilles de pollastre" },
    description: { es: "Crujientes, con queso fundido y pollo especiado.", ca: "Cruixents, amb formatge fos i pollastre especiat." },
    timeMin: 15,
    costTier: 1,
    difficulty: "easy",
    tags: ["mexican", "quick", "chicken", "budget"],
    imageUrl: "https://images.unsplash.com/photo-1628430044262-fb84cffbb744?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NzYzMDZ8MHwxfHNlYXJjaHwxfHxjaGlja2VuJTIwcXVlc2FkaWxsYXxlbnwwfDB8fHwxNzcxMjg1ODUyfDA&ixlib=rb-4.1.0&q=80&w=1080",
    active: 1,
    ingredients: [
      { name: { es: "Pechuga de pollo", ca: "Pit de pollastre" }, qty: 400, unit: "g", category: "meat" },
      { name: { es: "Tortillas de trigo", ca: "Tortilles de blat" }, qty: 8, unit: "u", category: "carbs" },
      { name: { es: "Queso rallado", ca: "Formatge ratllat" }, qty: 200, unit: "g", category: "dairy" },
      { name: { es: "Pimiento rojo", ca: "Pebrot vermell" }, qty: 1, unit: "u", category: "produce" },
      { name: { es: "Comino", ca: "Comí" }, qty: 1, unit: "cdta", category: "spices", pantry: true },
      { name: { es: "Aceite de oliva", ca: "Oli d'oliva" }, qty: 1, unit: "cda", category: "sauces", pantry: true },
    ],
    steps: {
      es: [
        "Preparar relleno\n• Corta el pollo en dados pequeños y el pimiento en tiras.\n• Saltea con comino, sal y aceite 5-6 min.",
        "Montar quesadillas\n• Pon una tortilla en sartén.\n• Añade queso, pollo con pimiento, más queso.\n• Cubre con otra tortilla.",
        "Tostar\n• Cocina 2 min por lado a fuego medio hasta que esté dorada y el queso fundido.\n• Corta en triángulos y sirve.",
      ],
      ca: [
        "Preparar farcit\n• Talla el pollastre en daus petits i el pebrot en tires.\n• Salteja amb comí, sal i oli 5-6 min.",
        "Muntar quesadilles\n• Posa una tortilla a la paella.\n• Afegeix formatge, pollastre amb pebrot, més formatge.\n• Cobreix amb una altra tortilla.",
        "Torrar\n• Cuina 2 min per costat a foc mitjà fins que estigui daurada i el formatge fos.\n• Talla en triangles i serveix.",
      ],
    },
  },
  {
    id: "poke_bowl_salmon",
    title: { es: "Poke bowl de salmón", ca: "Poke bowl de salmó" },
    description: { es: "Bowl hawaiano fresco con salmón, arroz y aguacate.", ca: "Bowl hawaià fresc amb salmó, arròs i alvocat." },
    timeMin: 20,
    costTier: 3,
    difficulty: "easy",
    tags: ["hawaiian", "fish", "healthy"],
    imageUrl: "https://images.unsplash.com/photo-1604259597308-5321e8e4789c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NzYzMDZ8MHwxfHNlYXJjaHwxfHxzYWxtb24lMjBwb2tlJTIwYm93bHxlbnwwfDB8fHwxNzcxMjg1ODUzfDA&ixlib=rb-4.1.0&q=80&w=1080",
    active: 1,
    ingredients: [
      { name: { es: "Salmón fresco (sushi grade)", ca: "Salmó fresc (sushi grade)" }, qty: 400, unit: "g", category: "fish" },
      { name: { es: "Arroz", ca: "Arròs" }, qty: 300, unit: "g", category: "carbs" },
      { name: { es: "Aguacate", ca: "Alvocat" }, qty: 2, unit: "u", category: "produce" },
      { name: { es: "Pepino", ca: "Cogombre" }, qty: 1, unit: "u", category: "produce" },
      { name: { es: "Salsa de soja", ca: "Salsa de soja" }, qty: 3, unit: "cda", category: "sauces", pantry: true },
      { name: { es: "Aceite de sésamo", ca: "Oli de sèsam" }, qty: 1, unit: "cda", category: "sauces" },
      { name: { es: "Semillas de sésamo", ca: "Llavors de sèsam" }, qty: 2, unit: "cda", category: "nuts" },
    ],
    steps: {
      es: [
        "Preparar arroz\n• Cuece el arroz y déjalo enfriar ligeramente.\n• Puedes aliñarlo con un poco de vinagre de arroz.",
        "Marinar el salmón\n• Corta el salmón en cubos de 2 cm.\n• Mezcla con soja y aceite de sésamo.\n• Deja marinar 10 min mientras preparas el resto.",
        "Montar los bowls\n• Pon arroz en el fondo de cada bol.\n• Coloca salmón marinado, aguacate en láminas y pepino en rodajas.\n• Espolvorea semillas de sésamo.\n• Sirve frío.",
      ],
      ca: [
        "Preparar arròs\n• Cou l'arròs i deixa'l refredar lleugerament.\n• Pots amanir-lo amb una mica de vinagre d'arròs.",
        "Marinar el salmó\n• Talla el salmó en cubs de 2 cm.\n• Barreja amb soja i oli de sèsam.\n• Deixa marinar 10 min mentre prepares la resta.",
        "Muntar els bols\n• Posa arròs al fons de cada bol.\n• Col·loca salmó marinat, alvocat en làmines i cogombre en rodanxes.\n• Espolvoreja llavors de sèsam.\n• Serveix fred.",
      ],
    },
  },
  {
    id: "pasta_pesto_pollo",
    title: { es: "Pasta al pesto con pollo", ca: "Pasta al pesto amb pollastre" },
    description: { es: "Cremosa, rápida y siempre apetece. Pesto de bote = zero esfuerzo.", ca: "Cremosa, ràpida i sempre apeteix. Pesto de pot = zero esforç." },
    timeMin: 18,
    costTier: 2,
    difficulty: "easy",
    tags: ["italian", "pasta", "quick", "chicken"],
    imageUrl: "https://images.unsplash.com/photo-1564813227527-a99b83712e45?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NzYzMDZ8MHwxfHNlYXJjaHwxfHxwZXN0byUyMGNoaWNrZW4lMjBwYXN0YXxlbnwwfDB8fHwxNzcxMjg1ODU1fDA&ixlib=rb-4.1.0&q=80&w=1080",
    active: 1,
    ingredients: [
      { name: { es: "Pasta (fusilli o penne)", ca: "Pasta (fusilli o penne)" }, qty: 400, unit: "g", category: "carbs" },
      { name: { es: "Pechuga de pollo", ca: "Pit de pollastre" }, qty: 400, unit: "g", category: "meat" },
      { name: { es: "Pesto (bote)", ca: "Pesto (pot)" }, qty: 150, unit: "g", category: "sauces" },
      { name: { es: "Tomates cherry", ca: "Tomàquets cherry" }, qty: 250, unit: "g", category: "produce" },
      { name: { es: "Queso parmesano", ca: "Formatge parmesà" }, qty: 40, unit: "g", category: "dairy" },
      { name: { es: "Aceite de oliva", ca: "Oli d'oliva" }, qty: 1, unit: "cda", category: "sauces", pantry: true },
    ],
    steps: {
      es: [
        "Cocinar pasta y pollo\n• Cuece la pasta al dente. Reserva agua de cocción.\n• Mientras, corta el pollo en tiras y saltea con aceite y sal 5-6 min.",
        "Mezclar\n• Corta los cherry por la mitad.\n• Escurre la pasta y mezcla con el pesto, el pollo y los cherry.\n• Añade un chorrito de agua de cocción para aflojar.\n• Sirve con parmesano rallado.",
      ],
      ca: [
        "Cuinar pasta i pollastre\n• Cou la pasta al dente. Reserva aigua de cocció.\n• Mentrestant, talla el pollastre en tires i salteja amb oli i sal 5-6 min.",
        "Barrejar\n• Talla els cherry per la meitat.\n• Escorre la pasta i barreja amb el pesto, el pollastre i els cherry.\n• Afegeix un raig d'aigua de cocció per afluixar.\n• Serveix amb parmesà ratllat.",
      ],
    },
  },
  {
    id: "burritos_ternera",
    title: { es: "Burritos de ternera", ca: "Burritos de vedella" },
    description: { es: "Burritos jugosos con arroz, carne y todo lo bueno.", ca: "Burritos sucosos amb arròs, carn i tot el bo." },
    timeMin: 25,
    costTier: 2,
    difficulty: "easy",
    tags: ["mexican", "beef", "comfort"],
    imageUrl: "https://images.unsplash.com/photo-1719948515819-71265e1abb0d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NzYzMDZ8MHwxfHNlYXJjaHwxfHxiZWVmJTIwYnVycml0b3xlbnwwfDB8fHwxNzcxMjg1ODU3fDA&ixlib=rb-4.1.0&q=80&w=1080",
    active: 1,
    ingredients: [
      { name: { es: "Carne picada de ternera", ca: "Carn picada de vedella" }, qty: 500, unit: "g", category: "meat" },
      { name: { es: "Tortillas grandes", ca: "Tortilles grans" }, qty: 4, unit: "u", category: "carbs" },
      { name: { es: "Arroz", ca: "Arròs" }, qty: 200, unit: "g", category: "carbs" },
      { name: { es: "Alubias negras (bote)", ca: "Mongetes negres (pot)" }, qty: 1, unit: "u", category: "cans" },
      { name: { es: "Queso rallado", ca: "Formatge ratllat" }, qty: 100, unit: "g", category: "dairy" },
      { name: { es: "Lechuga", ca: "Enciam" }, qty: 0.5, unit: "u", category: "produce" },
      { name: { es: "Comino", ca: "Comí" }, qty: 1, unit: "cdta", category: "spices", pantry: true },
      { name: { es: "Pimentón", ca: "Pebre vermell" }, qty: 1, unit: "cdta", category: "spices", pantry: true },
    ],
    steps: {
      es: [
        "Preparar arroz y carne\n• Cuece el arroz y reserva.\n• Saltea la carne con comino, pimentón y sal 6-7 min.\n• Escurre las alubias y añádelas a la carne 2 min más.",
        "Montar burritos\n• Calienta las tortillas en microondas 15 seg.\n• Pon arroz, carne con alubias, queso y lechuga.\n• Enrolla doblando los lados primero.",
        "Tostar (opcional)\n• Pon el burrito en sartén con el cierre abajo.\n• Tuesta 1-2 min por lado para sellarlo.",
      ],
      ca: [
        "Preparar arròs i carn\n• Cou l'arròs i reserva.\n• Salteja la carn amb comí, pebre vermell i sal 6-7 min.\n• Escorre les mongetes i afegeix-les a la carn 2 min més.",
        "Muntar burritos\n• Escalfa les tortilles al microones 15 seg.\n• Posa arròs, carn amb mongetes, formatge i enciam.\n• Enrotlla doblegant els costats primer.",
        "Torrar (opcional)\n• Posa el burrito a la paella amb el tancament avall.\n• Torra 1-2 min per costat per segellar-lo.",
      ],
    },
  },
  {
    id: "pasta_aglio_olio",
    title: { es: "Pasta aglio e olio con gambas", ca: "Pasta aglio e olio amb gambes" },
    description: { es: "Italiana minimalista: ajo, aceite, guindilla y gambas.", ca: "Italiana minimalista: all, oli, bitxo i gambes." },
    timeMin: 15,
    costTier: 2,
    difficulty: "easy",
    tags: ["italian", "pasta", "quick", "seafood"],
    imageUrl: "https://images.unsplash.com/photo-1638933482397-bc6189939ef3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NzYzMDZ8MHwxfHNlYXJjaHwxfHxnYXJsaWMlMjBvaWwlMjBzaHJpbXAlMjBwYXN0YXxlbnwwfDB8fHwxNzcxMjg1ODgwfDA&ixlib=rb-4.1.0&q=80&w=1080",
    active: 1,
    ingredients: [
      { name: { es: "Espaguetis", ca: "Espaguetis" }, qty: 400, unit: "g", category: "carbs" },
      { name: { es: "Gambas peladas", ca: "Gambes pelades" }, qty: 300, unit: "g", category: "fish" },
      { name: { es: "Ajo", ca: "All" }, qty: 6, unit: "diente", category: "produce", pantry: true },
      { name: { es: "Guindilla seca", ca: "Bitxo sec" }, qty: 2, unit: "u", category: "spices", pantry: true },
      { name: { es: "Perejil fresco", ca: "Julivert fresc" }, qty: 1, unit: "manojo", category: "produce" },
      { name: { es: "Aceite de oliva virgen extra", ca: "Oli d'oliva verge extra" }, qty: 6, unit: "cda", category: "sauces", pantry: true },
    ],
    steps: {
      es: [
        "Cocer la pasta\n• Cuece los espaguetis al dente en agua bien salada.\n• Reserva un vaso grande de agua de cocción.",
        "Hacer la salsa\n• Lamina el ajo finamente.\n• En sartén grande, calienta el aceite a fuego medio-bajo.\n• Dora el ajo lentamente con la guindilla troceada (2-3 min).\n• Añade las gambas y saltea 2 min.\n_CONSEJO: No quemes el ajo, se amarga._",
        "Emulsionar\n• Añade la pasta escurrida a la sartén.\n• Agrega agua de cocción poco a poco, removiendo.\n• El almidón + aceite creará una salsa sedosa.\n• Añade perejil picado y sirve.",
      ],
      ca: [
        "Coure la pasta\n• Cou els espaguetis al dente en aigua ben salada.\n• Reserva un got gran d'aigua de cocció.",
        "Fer la salsa\n• Lamina l'all finament.\n• En paella gran, escalfa l'oli a foc mitjà-baix.\n• Daura l'all lentament amb el bitxo trossejat (2-3 min).\n• Afegeix les gambes i salteja 2 min.\n_CONSELL: No cremis l'all, s'amarga._",
        "Emulsionar\n• Afegeix la pasta escorreguda a la paella.\n• Agrega aigua de cocció poc a poc, remenant.\n• El midó + oli crearà una salsa sedosa.\n• Afegeix julivert picat i serveix.",
      ],
    },
  },
  {
    id: "bowl_lentejas_verduras",
    title: { es: "Bowl de lentejas con verduras asadas", ca: "Bowl de llenties amb verdures rostides" },
    description: { es: "Nutritivo, económico y lleno de sabor. Meal prep perfecto.", ca: "Nutritiu, econòmic i ple de sabor. Meal prep perfecte." },
    timeMin: 30,
    costTier: 1,
    difficulty: "easy",
    tags: ["vegetarian", "budget", "healthy", "meal-prep"],
    imageUrl: "https://images.unsplash.com/photo-1735233024815-7986206a18a9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4NzYzMDZ8MHwxfHNlYXJjaHwxfHxsZW50aWwlMjByb2FzdGVkJTIwdmVnZXRhYmxlJTIwYm93bHxlbnwwfDB8fHwxNzcxMjg1ODYwfDA&ixlib=rb-4.1.0&q=80&w=1080",
    active: 1,
    ingredients: [
      { name: { es: "Lentejas cocidas (bote)", ca: "Llenties cuites (pot)" }, qty: 2, unit: "u", category: "cans" },
      { name: { es: "Boniato", ca: "Moniato" }, qty: 2, unit: "u", category: "produce" },
      { name: { es: "Brócoli", ca: "Bròcoli" }, qty: 300, unit: "g", category: "produce" },
      { name: { es: "Cebolla roja", ca: "Ceba vermella" }, qty: 1, unit: "u", category: "produce" },
      { name: { es: "Tahini", ca: "Tahini" }, qty: 3, unit: "cda", category: "sauces" },
      { name: { es: "Limón", ca: "Llimona" }, qty: 1, unit: "u", category: "produce" },
      { name: { es: "Comino", ca: "Comí" }, qty: 1, unit: "cdta", category: "spices", pantry: true },
      { name: { es: "Aceite de oliva", ca: "Oli d'oliva" }, qty: 3, unit: "cda", category: "sauces", pantry: true },
    ],
    steps: {
      es: [
        "Asar verduras\n• Precalienta horno a 220°C.\n• Corta boniato en cubos y brócoli en ramilletes.\n• Corta la cebolla en gajos.\n• Aliña con aceite, comino y sal.\n• Asa 20-25 min.",
        "Preparar lentejas y salsa\n• Calienta las lentejas con un chorrito de aceite y sal.\n• Mezcla tahini con zumo de limón y agua hasta hacer una salsa líquida.",
        "Montar el bowl\n• Pon lentejas en la base.\n• Coloca las verduras asadas encima.\n• Rocía con la salsa de tahini.",
      ],
      ca: [
        "Rostir verdures\n• Preescalfa forn a 220°C.\n• Talla moniato en cubs i bròcoli en ramets.\n• Talla la ceba en gajos.\n• Amaneix amb oli, comí i sal.\n• Rosteix 20-25 min.",
        "Preparar llenties i salsa\n• Escalfa les llenties amb un raig d'oli i sal.\n• Barreja tahini amb suc de llimona i aigua fins fer una salsa líquida.",
        "Muntar el bowl\n• Posa llenties a la base.\n• Col·loca les verdures rostides a sobre.\n• Ruixa amb la salsa de tahini.",
      ],
    },
  },
];
